### ISSUE TITLE
Error in EDM model when using ODataApiExplorer with JSON columns

### ISSUE THREAD

**Issue by mathew-tolj** [dotnet/aspnet-api-versioning#1113]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I recently configured JSON columns in a service using Microsoft.EntityFrameworkCore.SqlServer 8.0.10 and this caused Swashbuckle.AspNetCore 6.8.1 to fail. Investigating further it looks like this might be caused by the EDM model created by Asp.Versioning.OData.ApiExplorer 8.1.0 failing validation. It seems like the EDM model is expecting the owned entities from the JSON to have a key but in my case they are more like value objects. The exception  only causes Swashbuckle to fail. I can still call the endpoint and get a response using methods other than the Swagger endpoint.

### Steps To Reproduce

Create an entity that owns a list of other entities:

```csharp
public class Customer
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public string Name { get; set; } = string.Empty;

    public ICollection<Address> Addresses { get; } = [];
}
```

```csharp
public class Address
{
    public string Street { get; set; } = string.Empty;

    public string City { get; set; } = string.Empty;
}
```

Configure a `DbContext` that persists the list in database as JSON:

```csharp
public class ReproContext : DbContext
{
    public DbSet<Customer> Customers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Customer>()
            .OwnsMany(
                customer => customer.Addresses,
                addressesBuilder =>
                {
                    addressesBuilder.ToJson();
                });
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Data Source=(local);Encrypt=False;Initial Catalog=Repro;Integrated Security=True;Persist Security Info=False")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
    }
}
```

Create a controller for the entity:

```csharp
[ApiController]
[ApiVersion("1.0")]
[Route("[controller]")]
public class CustomerController(ReproContext context) : ControllerBase
{
    [HttpGet]
    [Produces("application/json")]
    [ProducesResponseType(typeof(IEnumerable<Customer>), StatusCodes.Status200OK)]
    public IActionResult Get(ODataQueryOptions<Customer> options) => Ok(options.ApplyTo(context.Customers.AsQueryable()));
}
```

Wire it all up in Program.cs:

```csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddDbContext<ReproContext>();

builder.Services.AddControllers().AddOData();

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle.
builder.Services.AddApiVersioning().AddODataApiExplorer();
builder.Services.AddTransient<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerGenOptions>();
builder.Services.AddSwaggerGen();

WebApplication app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(
        options =>
        {
            // Build a swagger endpoint for each discovered API version.
            foreach (ApiVersionDescription apiVersionDescription in app.DescribeApiVersions())
            {
                options.SwaggerEndpoint($"/swagger/{apiVersionDescription.GroupName}/swagger.json", apiVersionDescription.GroupName.ToUpperInvariant());
            }
        });
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();
```

### Exceptions (if any)

```
System.InvalidOperationException: The entity type 'ODataApiExplorerException.Address' of navigation property 'Addresses' on structural type 'ODataApiExplorerException.Customer' does not have a key defined.
    at Microsoft.OData.ModelBuilder.ODataModelBuilder.ValidateModel(IEdmModel model)
    at Microsoft.OData.ModelBuilder.ODataConventionModelBuilder.ValidateModel(IEdmModel model)
    at Microsoft.OData.ModelBuilder.ODataModelBuilder.GetEdmModel()
    at Microsoft.OData.ModelBuilder.ODataConventionModelBuilder.GetEdmModel()
    at Asp.Versioning.OData.VersionedODataModelBuilder.BuildModelPerApiVersion(IReadOnlyList`1 apiVersions, IReadOnlyList`1 configurations, List`1 models, String routePrefix)
    at Asp.Versioning.OData.VersionedODataModelBuilder.GetEdmModels(String routePrefix)
    at Asp.Versioning.ApiExplorer.PartialODataDescriptionProvider.OnProvidersExecuting(ApiDescriptionProviderContext context)
    at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
    at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0.403

**Comment by commonsensesoftware** [comment]
This _might_ be a gap in the implementation. I can tell by what you've shared that you are in the _Partial OData_ camp. You're not really using OData the protocol. You're just taking advantage of the query options. There's nothing wrong with that per se and why reinvent a HTTP-based query language.

This path, however, does come with some quirks and limitations. First and foremost, the API Explorer extensions for OData are based on an EDM. EF and OData both use EDM, but not the **same** EDM model or instance. The EDM for EF is about mapping your model to a database. The OData EDM is for mapping your model over the wire (e.g. HTTP). You don't have an OData EDM (that I see). That is to be expected in this scenario. Since the API Explorer extensions only know how to operate on an OData EDM, it generates one on the fly.

It appears you've encountered a sharp edge where:

1. The implementation, or default implementation, doesn't do the right thing
2. Additional information is required to generate the proper EDM (for OData)

I'm almost certain it's `#2`. You need to tell the OData side that the `Addresses` is either _contained_ or a _complex type_.  This configuration can be achieved by using `IModelConfiguration`, which will be picked up by DI or you can explicitly configure it through `ODataApiExplorerOptions.AdHocModelBuilder`. This is the `ODataModelBuilder` that is used to build the ad hoc EDM used for this scenario.

The reason you haven't seen this before is that you aren't actually using OData in your controller. That requires applying `[ODataRouting]`, which is typically applied by inheriting from `ODataController`.

I think with a little bit of configuration help on your side, you'll achieve the result you're looking for.

**Comment by mathew-tolj** [comment]
Thanks to your guidance I have been able to make some progress on this. I have run into a related issue and I am unsure if it is my lack of EDM model knowledge, if I am implementing the versioning incorrectly, or if it is actually a bug.

To configure the model to solve the original issue, I have added a model configuration:

```csharp
public class CustomerModelConfiguration : IModelConfiguration
{
    public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string? routePrefix)
    {
        _ = builder.EntitySet<Customer>("Customers");
        _ = builder.ComplexType<Address>();
    }
}
```

This works fine but in my production code the entity causing the issue is only in version 2 of the API so I added a check against the API version to only configure the model for version 2:

```csharp
public class CustomerModelConfiguration : IModelConfiguration
{
    private static readonly ApiVersion s_version1 = new(1, 0);

    public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string? routePrefix)
    {
        if (apiVersion > s_version1)
        {
            _ = builder.EntitySet<Customer>("Customers");
            _ = builder.ComplexType<Address>();
        }
    }
}
```

With this check in place the exception will still occur when processing version 1. This error appears to short circuit the configuration process and version 2 is never configured. I have tried casting the builder to `ODataConventionModelBuilder` and calling `Ignore` for the types when configuring version 1 but it does not seem to have helped. Is there a better way for me to handle this without configuring the types for versions where they are not used?

**Comment by commonsensesoftware** [comment]
Hmm... This _might_ actually be a bug. The generated EDM is **only** created and used by API Explorer. It's actually ephemeral. The workaround _should_ be to use the same model configuration for every API version. I'll have to dig deeper as to why it still causes a problem. A distinct EDM is created for each API version. I wouldn't expect an explicit `Ignore` to have any effect because it's not in the EDM unless you put it there first. Nothing is automatic.

**Comment by commonsensesoftware** [comment]
Did you ever make progress on this? I realized that I could have provided a little bit more information. If you do **not** configure something in the EDM, it will not exist, which is an entirely different problem. Based on your description, I would expect an implementation that is more like:

```c#
public class CustomerModelConfiguration : IModelConfiguration
{
    private static readonly ApiVersion s_version1 = new(1, 0);

    public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string? routePrefix)
    {
        var customers = builder.EntitySet<Customer>("Customers");

        if (apiVersion > s_version1)
        {
            builder.ComplexType<Address>();
        }
        else
        {
            builder.Entity.Ignore(c => c.Addresses);
        }
    }
}
```

**Comment by mathew-tolj** [comment]
Sorry for the delay. I had moved on from this project and it took me some time to get it back into this state again to check where I had got to.

In my case it wasn't just that the properties were different, there were completely different entities in V1 vs V2. No matter what I tried the complex types were still being detected by convention and treated as entities unless explicitly configured.

The conclusion that I reached was that trying to build different models conditionally by checking versions didn't work and that I should define all entities from all versions in a single model as a workaround (which I think you tried to tell me earlier but it took a while to sink in).

```csharp
public class CustomerModelConfiguration : IModelConfiguration
{
    public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string? routePrefix)
    {
        builder.EntitySet<CustomerV1>();

        builder.EntitySet<CustomerV2>();
        builder.ComplexType<Address>();
    }
}
```

The exception no longer occurs when I do this and the output of the swagger endpoint looks correct for each version.

I left this open because it seemed like you thought the conditional statements should have worked and that there might be a bug.

**Comment by commonsensesoftware** [comment]
Thanks for the update. I think I understand what happened. When your model configuration is invoked to configure the builder for the EDM, it is the `ODataConventionModelBuilder`. Once you add a definition to it, it will implicitly grab everything. It may not know or may incorrectly map the relationship (aka navigation) between entities and/or other types.

A `IModelConfiguration` is called for every discovered API version. You should not exclude an entity unless it really does not apply to that API version at all. Based on your example, I cannot tell if `CustomerV1` and `CustomerV2` apply to all API versions or whether they have API affinity. You _can_ use a single `Customer` type if it makes sense, but then you will likely need to configure what does or does not apply to that specific version. The full OData OpenAPI example probably has the best example of this for _People_:

https://github.com/dotnet/aspnet-api-versioning/blob/bd469de0990a8c3e20bf96d511038755928b5dc5/examples/AspNetCore/OData/ODataOpenApiExample/Configuration/PersonModelConfiguration.cs

The configuration starts with everything and then selectively removes parts that do not apply to the specified API version by using `Ignore`. This is all achieved using a single `Person` class. OData will selectively only yield the members defined in the current EDM over the wire. The trickier part is the API Explorer. It doesn't know anything about the EDM and it only works on a `Type` via Reflection. The API Explorer extensions use the EDM and source `Type` to create a new, version-specific type that only includes the defined properties. The generated types are not executable. It just gives the API Explorer something to inspect. This allows you to define a single class and then slice and dice it for different use cases. This is really useful if you simply add, or possibly remove, specific members between API versions. This will flow through the entire hierarchy as well; for example, if `Customer` looks the same, but `Address` changed across versions that will be handled. This feature is referred to as _Model Substitution_. There are no knobs to turn. You either let the API Explorer do its thing and substitute as it sees fit or you provide a different model per API version. Ultimately, the goal was to have a single set of models, configure how they look over the wire with the EDM, and then have the API Explorer do all the work to make things look the way the EDM defined them for that particular API version.

It looks like you got things working now. I'm not seeing anything else to follow up on. I'll give you a chance to reply and then I think we can close this out. 😉 Feel free to ask any other questions if you have them.

**Comment by commonsensesoftware** [comment]
This issue has reached its conclusion. Feel free to reopen or ask additional questions if they come up.
