### ISSUE TITLE
ArgumentNullException in SwaggerODataSample with .net 6

### ISSUE THREAD

**Issue by MuhKuh7** [dotnet/aspnet-api-versioning#796]
The example project SwaggerODataSample with Microsoft.AspNetCore.OData.Versioning.ApiExplorer version 5.0.0 works fine when I target .net 5, but when switching to .net 6, I get the following exception:

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'type')
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Microsoft.AspNet.OData.DefaultContainerBuilder.BuildContainer()
   at Microsoft.AspNet.OData.PerRouteContainerBase.CreateODataRootContainer(Action`1 configureAction)
   at Microsoft.AspNet.OData.PerRouteContainerBase.CreateODataRootContainer(String routeName, Action`1 configureAction)
   at Microsoft.AspNet.OData.Extensions.ODataEndpointRouteBuilderExtensions.MapODataRoute(IEndpointRouteBuilder builder, String routeName, String routePrefix, Action`1 configureAction)
   at Microsoft.AspNet.OData.Extensions.IEndpointRouteBuilderExtensions.MapVersionedODataRoute(IEndpointRouteBuilder builder, String routeName, String routePrefix, IEnumerable`1 models)
   at Microsoft.AspNet.OData.Extensions.IEndpointRouteBuilderExtensions.MapVersionedODataRoute(IEndpointRouteBuilder builder, String routeName, String routePrefix, VersionedODataModelBuilder modelBuilder)
   at Microsoft.Examples.Startup.<>c__DisplayClass1_0.<Configure>b__0(IEndpointRouteBuilder endpoints) in C:\SwaggerODataSample\Startup.cs:line 78
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Microsoft.Examples.Startup.Configure(IApplicationBuilder app, VersionedODataModelBuilder modelBuilder, IApiVersionDescriptionProvider provider) in C:\SwaggerODataSample\Startup.cs:line 74
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)

```

**Comment by vsoldatkin** [comment]
I've encountered this problem too. It appears DefaultContianerBuilder is not compatible with .net 6. 

A strange reflection logic in DefaultContainerBuilder.BuildContainer() (in my case in OData 7.3.0) supposes that the types ServiceCollection and ServiceCollectionContainerBuilderExtensions reside in the same assembly, which is not the case in .net 6. 

Upgrading the AspNetCore.OData package to the latest version 7.5.12 (I specificly target 7.* versions only) solved this to me. Otherwise it may be possible to solve this by implementing your own ContainerBuilder based on DefaultContainerBuilder code.

**Comment by markhealy88** [comment]
Thanks @vsoldatkin I had the same issue on Microsoft.AspNetCore.OData 7.5.8 and updating to 7.5.12 fixed it for me

**Comment by commonsensesoftware** [comment]
>**Disclaimer**: OData is not _officially_ support on .NET 5.0 or 6.0.

OData has historical had some internal DI guts that have to be changed and are difficult to replicate. It's always been the lesser of two evils. I've had both bite me between version upgrades.

1. Duplicate the original container setup. Sounds reasonable, but when things change in between versions, things break. There's no public way to call into what the default DI setup does.
2. Use Reflection to map a function to what the internal OData DI setup does. Yucky, but tends to stay aligned between versions; however, as you are seeing, not always.

It's been a while since I've looked at how things will be changing when I _finally_ get the OData support done. I've always hated this quirk and I think I've finally been able to get away from it.

I'm hoping to announce the upcoming roadmap and catch OData up.

**Comment by commonsensesoftware** [comment]
Ultimately, this has not been a supported scenario or configuration. The `6.0` is just around the corner. It will support .NET 6.0 and OData 8. You can see and play with the latest OData code bits [here](../tree/main/examples/AspNetCore/OData). Since this is a duplicate issue and there's no further action, I'm going to close it out. If you discover any issues with the new implementation, feel free to open new issues. Thanks.
