### ISSUE TITLE
Swagger with OData Endpoint Mappings

### ISSUE THREAD

**Issue by kRaBby** [dotnet/aspnet-api-versioning#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to setup Swagger (Swashbuckle.AspNetCore) for OData enpoints.
I have found your example SomeODataOpenApiExample project. I tried to implement the same way on my project but faced an issue: 
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Asp.Versioning.ApiExplorer.ODataApiDescriptionProvider.TryMatchModelVersion(ApiDescription description, IReadOnlyList`1 items, IODataRoutingMetadata& metadata)
         at Asp.Versioning.ApiExplorer.ODataApiDescriptionProvider.OnProvidersExecuted(ApiDescriptionProviderContext context)
         at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
         at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
I investigated and have found that your library is not supported OData Endpoint Mappings methods. When I add Edm model to your example it also fails.set up

### Describe the solution you'd like

I would like to be able to add:
```
builder.Services.AddControllers()
                .AddOData( options => options.Select()
                .AddRouteComponents( "/api/2.0", GetEdmModel() )
                );

Microsoft.OData.Edm.IEdmModel GetEdmModel()
{
    var builder = new ODataConventionModelBuilder();
    builder.DataServiceVersion = new Version( "2.0" );
    builder.EntitySet<Book>( "Books" );

    return builder.GetEdmModel();
}
```
and still able to use your lib with Swagger.

**Comment by commonsensesoftware** [comment]
Based your description, it appears to want to use all of OData and not just _some_ of it. The **SomeODataOpenApiExample** project is meant for people that have non-OData endpoints, but still use OData query options and want to document them with OpenAPI. The example you are looking for is [ODataOpenApiExample](../blob/main/examples/AspNetCore/OData/ODataOpenApiExample).

Unfortunately, the out-of-the-box OData configuration will not work. I tried to work with the OData team when 8.0 was in the early preview, but they elected to not change their design or provide any hooks that would allow extenders such as API Versioning to integrate smoother. As a result, API Versioning requires its own, separate (but similar) OData configuration. The required setup should look something like:

```c#
var services = builder.Services;

// this will define query options for the entire application.
// any calls to AddRouteComponents here will be ignored by
// api versioning
services.AddControllers().AddOData(options => options.Select());

services.AddApiVersioning(
            options =>
            {
                // not strictly necessary, but the default supports query string
                // and url segment, which will affect documentation
                options.ApiVersionReader = new UrlSegmentApiVersionReader();
            })
        .AddOData(
            options =>
            {
                // there's no "magic", api version route constraint is necessary
                // when versioning by url segment so api versioning knwows how
                // to find it in the url.
                options.AddRouteComponents( "api/{version:apiVersion}" );
    
                // the default is "() => new ODataConventionModelBuilder().EnableLowerCamelCase()",
                // which covers 90%+ of odata use cases. this method is called
                // and a new builder is created for every api version
                options.ModelBuilder.ModelBuilderFactory = () => new ODataConventionModelBuilder(); 

                // this is where things really start to change. api versioning uses one edm per
                // api version and optionally with a route prefix. this configuration can be quite
                // large, so most people will define implementations of IModelConfiguration, which
                // are automatically picked up by dependency injection
                options.ModelBuilder.DefaultModelConfiguration = (builder, version, prefix) =>
                {
                    // only build an edm for 2.0
                    if (version != new ApiVersion(2.0))
                    {
                        return;
                    }

                    builder.DataServiceVersion = new Version("2.0");
                    builder.EntitySet<Book>("Books");
                };
            })
        .AddODataApiExplorer(
            options =>
            {
                // defines the format "'v'major[.minor][-status]" for api version, which
                // will be used for grouping and displayed in the OpenAPI UI
                options.GroupNameFormat = "'v'VVV";

                // this will transform the template "api/{version:apiVersion}" to "api/2.0"
                // explored endpoints
                options.SubstituteApiVersionInUrl = true;
            }
        );
```

Once your configuration is updated, you should get the results that you want.

**Comment by commonsensesoftware** [comment]
This thread seems to have gone idle. I presume you got it working using my guidance. As there is no further action, I'm closing this issue out. If things are still not working or you need additional help, feel free to come back or reopen the issue.
