### ISSUE TITLE
Exception When Exploring OData Routes with Both Key Styles

### ISSUE THREAD

**Issue by commonsensesoftware** [dotnet/aspnet-api-versioning#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When:

```c#
options.RouteOptions.EnableKeyInParenthesis = false;
options.RouteOptions.EnableKeyAsSegment = true;
```

or

```c#
options.RouteOptions.EnableKeyInParenthesis = true;
options.RouteOptions.EnableKeyAsSegment = false;
```

Is configured, then OData routes are documented as expected. However, if:

```c#
options.RouteOptions.EnableKeyInParenthesis = true;
options.RouteOptions.EnableKeyAsSegment = true;
```

is configured or there is no configuration at all (the default), then an exception is encountered.

### Expected Behavior

No exception should occur. If both key styles are enabled, then both routes should be discovered and documented.

### Steps To Reproduce

- Define entity with composite keys
- Configure both entity key types (or omit the configuration, which is the default)
- Enable the API Explorer extensions for OData
- Run the application

### Exceptions (if any)

**NullReferenceException**

```
at Asp.Versioning.ApiExplorer.ODataApiDescriptionProvider.TryMatchModelVersion(ApiDescription description, IReadOnlyList`1 items, IODataRoutingMetadata& metadata)
   at Asp.Versioning.ApiExplorer.ODataApiDescriptionProvider.OnProvidersExecuted(ApiDescriptionProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<GetSwaggerAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

### Anything else?

Related to #889

**Comment by commonsensesoftware** [comment]
There are actually two conditions that can cause this:

1. A logic bug where `ApiVersionMetadata` is not applied to all `SelectorModel` instances created by OData
2. A developer incorrectly calls `AddRouteComponents` via the default OData method instead of the API Versioning variant
