### ISSUE TITLE
OWIN + Versioning + OData + Web API + Swagger: System.InvalidOperationException: 'The container builder created by the container builder factory must not be null.'

### ISSUE THREAD

**Issue by AndreyIvaneneko** [dotnet/aspnet-api-versioning#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,
I am trying to use Swagger for OData and Web API simultaneously under OWIN in the test project and getting the error:
System.InvalidOperationException: 'The container builder created by the container builder factory must not be null.'

Now I am using Asp.Versionin.WebApi.* 7.0.0,  Microsoft.AspNet.OData 7.5.18, Swashbuckle.Core ..
It worked for the old versions Microsoft.AspNet.OData.Versioning.* 5.0.0, Microsoft.AspNet.WebApi.Versioning.* 4.1.1,  Microsoft.AspNet.OData 7.5.8, Swashbuckle.Core ..

Here is my startup:
public class Startup {
        public void Configuration(IAppBuilder builder) {
            var configuration = new HttpConfiguration();

            configuration.Routes.MapHttpRoute(
                           name: "DefaultApi",
                           routeTemplate: "api/{controller}/{action}/{id}",
                           defaults: new { id = RouteParameter.Optional }
                       );

            // create dynamic controllers
            MarketControllerBuilder.Build();
            PingControllerBuilder.Build();

            // handling error
            configuration.Services.Replace(typeof(IExceptionHandler), new CustomExceptionHandler());

            // include dynamic assemblies
            configuration.Services.Replace(typeof(IHttpControllerTypeResolver), new CustomHttpControllerTypeResolver());

            // reporting api versions will return the headers "api-supported-versions" and "api-deprecated-versions"
            configuration.AddApiVersioning(options => {
                options.ReportApiVersions = true;
            });

            configuration.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

            var modelBuilder = new VersionedODataModelBuilder(configuration) {
                ModelConfigurations =
                {
					new AllConfigurations()
                }
            };
            var models = modelBuilder.GetEdmModels();

            configuration.Count().Filter().OrderBy().Expand().Select().MaxTop(null);

            configuration.MapVersionedODataRoute("odata", "odata", models, ConfigureContainer);

            var apiExplorer = configuration.AddODataApiExplorer(
                options => {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });

            configuration.EnableSwagger(
                "{apiVersion}/swagger",
                swagger => {
                    // build a swagger document and endpoint for each discovered API version
                    swagger.MultipleApiVersions(
                        (apiDescription, version) => apiDescription.GetGroupName() == version,
                        info => {
                            foreach (var group in apiExplorer.ApiDescriptions) {
                                var description = "A sample application with Swagger, Swashbuckle, OData, and API versioning.";

                                if (group.IsDeprecated) {
                                    description += " This API version has been deprecated.";
                                }

                                info.Version(group.Name, $"Sample API {group.ApiVersion}")
                                    .Contact(c => c.Name("Some").Email("administrators@any.com"))
                                    .Description(description)
                                    .License(l => l.Name("MIT").Url("https://opensource.org/licenses/MIT"))
                                    .TermsOfService("Shareware");
                            }
                        });

                    // add query parameter
                    swagger.OperationFilter<QueryOperationFiler>();
                    // add a custom operation filter which documents the implicit API version parameter
                    swagger.OperationFilter<SwaggerDefaultValues>();

                    // integrate xml comments
                    swagger.IncludeXmlComments(XmlCommentsFilePath);
                })
                .EnableSwaggerUi(swagger => swagger.EnableDiscoveryUrlSelector());

            builder.UseAutofac(configuration);
            builder.UseWebApi(configuration);
        }
....
}

Is the case supported now? Maybe I missed something.

Thanks.

### Exceptions (if any)

System.InvalidOperationException: 'The container builder created by the container builder factory must not be null.'

**Comment by commonsensesoftware** [comment]
I was not able to reproduce this. Do you have the world's simplest repro? Where does this even happen?

I did notice that the automatic assembly binding redirection goes awry after updating to **Microsoft.AspNet.OData** in the sample project after `7.5.18`. It took me quite a while to figure out why, but it's related to **Newtonsoft.Json**. According to the _Fusion Log_, it's being demanded by **System.Net.Http.Formatting**. It's unclear why that isn't otherwise forwarded. Updating the **Newtonsoft.Json** version had everything working again. Here is what I used:

```xml
 <ItemGroup>
  <PackageReference Include="Microsoft.AspNet.OData" Version="7.5.18" /> <!-- 7.6.5 (current) works too -->
  <PackageReference Include="Microsoft.OData.Core" Version="7.15.0" />
  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  <PackageReference Include="Swashbuckle.Core" Version="5.6.0" />
 </ItemGroup>
```

From the OData code, it appears this scenario happens when a custom `PerRouteContainer.BuilderFactory` callback is set and the result of invoking it returns `null`. API Versioning never sets this property, which leads me to believe this is some other part of your configuration that hasn't be shared yet.

A repro would go a long way in using the same setup that you've used.

**Comment by AndreyIvaneneko** [comment]
Thank you for the reply, 
please, give me some time to simplify the solution to reproduce this case.

Here is just the stacktrace:
   at System.Web.Http.HttpConfigurationExtensions.GetODataRootContainer(HttpConfiguration configuration, IHttpRoute route) in /_/src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/System.Web.Http/HttpConfigurationExtensions.cs:line 88
   at Asp.Versioning.ApiExplorer.ODataApiExplorer.ExploreQueryOptions(IHttpRoute route, Collection`1 apiDescriptions) in /_/src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ApiExplorer/ODataApiExplorer.cs:line 290
   at Asp.Versioning.ApiExplorer.ODataApiExplorer.ExploreRouteControllers(IDictionary`2 controllerMappings, IHttpRoute route, ApiVersion apiVersion) in /_/src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ApiExplorer/ODataApiExplorer.cs:line 184
   at Asp.Versioning.ApiExplorer.VersionedApiExplorer.InitializeApiDescriptions() in /_/src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ApiExplorer/VersionedApiExplorer.cs:line 242
   at Asp.Versioning.ApiExplorer.VersionedApiExplorer.Initialize() in /_/src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ApiExplorer/VersionedApiExplorer.cs:line 209
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Asp.Versioning.ApiExplorer.VersionedApiExplorer.get_ApiDescriptions() in /_/src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ApiExplorer/VersionedApiExplorer.cs:line 60
...

**Comment by commonsensesoftware** [comment]
It looks like there was a change that happened way back here:

https://github.com/OData/WebApi/commit/cdb3cc2498561c20f8ac9dce90279ef1d089fdb7#diff-d0a0974759e897dd61084d34760b0c3dc5ac4311c83ad782d7a99d0c6323c9dc

that may be part of the culprit. These methods are needed to get information about the associated container, but since they are `internal`, there's no choice but to fork the code 😞 (or use Reflection 🤮). Amazingly, this has not be reported in 6+ years!

The changes are likely fairly simple, but I want to repro the conditions so that I know the issue has been properly fixed. Whatever is happening doesn't occur in any unit test, acceptance test, or example project. I _think_ it may be related to DI, but I'm not 100% sure.

**Comment by commonsensesoftware** [comment]
@AndreyIvaneneko Following up to see if you were able to provide any information that will reproduce the scenario. I have a rough idea of where the fix needs to happen, but I'm unsure how to setup the conditions. I want to configure the same scenario so that I can add a test case that will ensure it is fixed and will not regress in the future.

**Comment by bleepzter** [comment]
I think this is not just for OData. I have the same issue with regular API. Somehow the introduction of the ASP package forces some assembly binding redirects but not always. There is deffinetely ambiguity between http.routing and asp.versioing.routing.

**Comment by commonsensesoftware** [comment]
@bleepzter In what way? What _container_ would you be referring to? There isn't any out-of-the-box container or DI support for ASP.NET Web API. Do you have an repro or, at least, an error message?

**Comment by commonsensesoftware** [comment]
Last call. Checking back in. Did you ever find a solution or create a repro? I'm happy to dive into a solution, but I'm not sure what is required to produce these conditions. There is an [E2E example project](../tree/main/examples/AspNet/OData/OpenApiODataWebApiExample) that ties everything together. You can use that as the basis of the repro or compare it against your setup.

**Comment by commonsensesoftware** [comment]
Unfortunately, I've been able to reproduce the problem. There may definitely be some binding redirect issues (as noted above), but I've only found them to be related to `Newtonsoft.Json`. Based on the call stack provided, this is definitely happening in relation to OData in some capacity. Without a repro, I don't really have a way to continue the investigation. Something _may be_ happening inside the `ConfigureContainer` setup.

I don't mind diving into this further, but it would seem you've either moved on or don't have time to provide a repro. If you ever do or someone else runs into this issue, I'm happy to reopen the issue and continue the investigation.
